/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mefjgaqbxamxyfwuxbvl"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lZmpnYXFieGFteHlmd3V4YnZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjEwNDUsImV4cCI6MjA3MzE5NzA0NX0.U986yWCX8h-8eVGq5GBuw-HgdNZLt1ubp4zStCvCTIo"